language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

script:
  - cat requirements.txt requirements-ci.txt | safety check --stdin
  - radon cc elasticsearch_reindex -nb --total-average
  - isort elasticsearch_reindex --diff && isort tests --diff
  - flake8 ./
