language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

script:
  - cat requirements.txt requirements-ci.txt | safety check --stdin
  - radon cc main -nb --total-average
  - isort main --diff && isort tests --diff
  - flake8 ./

after_success:
  - coverage report -m && coverage xml
  - bash <(curl -s https://codecov.io/bash)
