version: "3"

services:
  elasticsearch-source:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    restart: always
    hostname: elasticsearch
    container_name: elasticsearch-source
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9201:9200

  elasticsearch-dest:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.0
    restart: always
    hostname: elasticsearch
    container_name: elasticsearch-dest
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9202:9200
